### ISSUE TITLE
add suport for images in html and css

### ISSUE THREAD

**Issue by bboydflo** [PDFTron/web-to-pdf#2]
**Is your feature request related to a problem? Please describe.**
I want to use images both as img tags inside html template and as a css background.

**Describe the solution you'd like**
I would like to be able to position images everywhere on the page and the option to stretch an image to fill the whole page.

**Additional context**
Some examples for the above features would be really nice.

**Comment by lbittner-pdftron** [comment]
Hey there, I added an example for including images in your HTML. 

Right now, we don't have support for CSS background image, but I will add that very soon

**Comment by bboydflo** [comment]
@lbittner-pdftron thanks. I actually managed to do some workaround:

```
.logo {
    background-image: url(data:image/png;base64,iVBOR...
	...
}
```
