### ISSUE TITLE
code issue: variable used before being defined

### ISSUE THREAD

**Issue by bboydflo** [PDFTron/web-to-pdf#3]
After some investigation in the source code I found this line: https://github.com/PDFTron/web-to-pdf/blob/master/src/index.js#L331 which seems to be incorrect. 

```js
const ree = Path.resolve(re, asset);
const re = Path.relative(ree, process.cwd());
```

`re` is used before it's defined.

**Comment by lbittner-pdftron** [comment]
Thank you! Will fix this soon

**Comment by lbittner-pdftron** [comment]
@bboydflo Your three issues have been fixed and pushed into master :) I also updated the [npm](https://www.npmjs.com/package/@pdftron/web-to-pdf) package.

Thanks!

**Comment by bboydflo** [comment]
> @bboydflo Your three issues have been fixed and pushed into master :) I also updated the [npm](https://www.npmjs.com/package/@pdftron/web-to-pdf) package.
> 
> Thanks!

Thank you alot for this project! It's a great project!
