### ISSUE TITLE
question: how do you handle printing long content and splitting into pages?

### ISSUE THREAD

**Issue by bboydflo** [PDFTron/web-to-pdf#6]
I found this project (https://www.pagedjs.org/) and I was wondering how splitting content into different pages is handled into this lib?

**Comment by bboydflo** [comment]
and the second question would be: can I get control completely over the styles? Let's say I only want to work with my pagedjs styles plus my custom styles but not `web-to-pdf` styles. I am afraid that both libraries try to fix the same thing but I would like full control over the styles.

Thanks for a nice lib!

**Comment by lbittner-pdftron** [comment]
Hi @bboydflo, sorry for the late reply!

This library does not apply very many styles, (you can see all of them [here](https://github.com/PDFTron/web-to-pdf/blob/master/src/styles/index.css)). Most of the styles in that stylesheet are used just for development, and the rest are just removing some paddings and margins to ensure the correct page size. All those styles are very generic so it should be easy to override them if you want!

This library will print your entire web page as a single PDF no matter how tall it is, unless you explicitly tell it where you want it to break the pages up. You can do this by wrapping your pages in a `.Page` div (you can also customize the page divide classname). You can [view the docs here](https://github.com/PDFTron/web-to-pdf/blob/master/documentation/creating-pages.md)

Let me know if theres any more questions!
